// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaUcZTRYaQDLNWg4cvsMIlsDWa0cHU6-g',
    appId: '1:168552599519:web:efbe171f0e29b0d41cfe6a',
    messagingSenderId: '168552599519',
    projectId: 'momentum-32f3e',
    authDomain: 'momentum-32f3e.firebaseapp.com',
    storageBucket: 'momentum-32f3e.firebasestorage.app',
    measurementId: 'G-046DEZ1K2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9gQVQqeC7QqH68MoSjcbWmz6zeIlBjTM',
    appId: '1:168552599519:android:94b15c08c130a1001cfe6a',
    messagingSenderId: '168552599519',
    projectId: 'momentum-32f3e',
    storageBucket: 'momentum-32f3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQjkirGhmTigVxD2iRGwDjXC_8dy40_us',
    appId: '1:168552599519:ios:4953abf01889a3151cfe6a',
    messagingSenderId: '168552599519',
    projectId: 'momentum-32f3e',
    storageBucket: 'momentum-32f3e.firebasestorage.app',
    androidClientId: '168552599519-3ln7sf9ms9qisthsuae6npvrcn3fj4os.apps.googleusercontent.com',
    iosClientId: '168552599519-28ocdhsfriop2p1ofuf8id73hunpiup6.apps.googleusercontent.com',
    iosBundleId: 'com.example.momentum',
  );

}